name: Validate

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-2025]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
            submodules: true

    - name: Build
      run: make all -j

    - name: Set permissions (POSIX)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        chmod +x .github/workflows/val.sh
        find validateFiles -type f -name '*.tst' -exec chmod +r {} +
        find testFiles -type f \( -name '*.fa' -o -name '*.fasta' -o -name '*.fa.gz' -o -name '*.fasta.gz' -o -name '*.gfa' \) -exec chmod +r {} +

    - name: Validate (POSIX)
      if: runner.os != 'Windows'
      shell: bash
      run: .github/workflows/val.sh

    - name: Validate (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: .\.github\workflows\val.bat
